//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.08 at 04:54:09 PM CET 
//


package com.lisilab.its.model.datashop;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}number_of_kcs"/>
 *         &lt;element ref="{}observations_with_kcs" minOccurs="0"/>
 *         &lt;element ref="{}number_of_parameters" minOccurs="0"/>
 *         &lt;element ref="{}logistic_regression_model_status"/>
 *         &lt;element ref="{}aic" minOccurs="0"/>
 *         &lt;element ref="{}bic" minOccurs="0"/>
 *         &lt;element ref="{}log_likelihood" minOccurs="0"/>
 *         &lt;element ref="{}cross_validation_status"/>
 *         &lt;element ref="{}unstratified_cross_validation_rmse" minOccurs="0"/>
 *         &lt;element ref="{}student_stratified_cross_validation_rmse" minOccurs="0"/>
 *         &lt;element ref="{}step_stratified_cross_validation_rmse" minOccurs="0"/>
 *         &lt;element ref="{}unstratified_number_of_parameters" minOccurs="0"/>
 *         &lt;element ref="{}unstratified_number_of_observations" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "numberOfKcs",
    "observationsWithKcs",
    "numberOfParameters",
    "logisticRegressionModelStatus",
    "aic",
    "bic",
    "logLikelihood",
    "crossValidationStatus",
    "unstratifiedCrossValidationRmse",
    "studentStratifiedCrossValidationRmse",
    "stepStratifiedCrossValidationRmse",
    "unstratifiedNumberOfParameters",
    "unstratifiedNumberOfObservations"
})
@XmlRootElement(name = "kc_model")
public class KcModel {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "number_of_kcs", required = true)
    protected BigInteger numberOfKcs;
    @XmlElement(name = "observations_with_kcs")
    protected BigInteger observationsWithKcs;
    @XmlElement(name = "number_of_parameters")
    protected BigInteger numberOfParameters;
    @XmlElement(name = "logistic_regression_model_status", required = true)
    protected String logisticRegressionModelStatus;
    protected BigDecimal aic;
    protected Float bic;
    @XmlElement(name = "log_likelihood")
    protected Float logLikelihood;
    @XmlElement(name = "cross_validation_status", required = true)
    protected String crossValidationStatus;
    @XmlElement(name = "unstratified_cross_validation_rmse")
    protected Float unstratifiedCrossValidationRmse;
    @XmlElement(name = "student_stratified_cross_validation_rmse")
    protected Float studentStratifiedCrossValidationRmse;
    @XmlElement(name = "step_stratified_cross_validation_rmse")
    protected Float stepStratifiedCrossValidationRmse;
    @XmlElement(name = "unstratified_number_of_parameters")
    protected BigInteger unstratifiedNumberOfParameters;
    @XmlElement(name = "unstratified_number_of_observations")
    protected BigInteger unstratifiedNumberOfObservations;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the numberOfKcs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfKcs() {
        return numberOfKcs;
    }

    /**
     * Sets the value of the numberOfKcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfKcs(BigInteger value) {
        this.numberOfKcs = value;
    }

    /**
     * Gets the value of the observationsWithKcs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObservationsWithKcs() {
        return observationsWithKcs;
    }

    /**
     * Sets the value of the observationsWithKcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObservationsWithKcs(BigInteger value) {
        this.observationsWithKcs = value;
    }

    /**
     * Gets the value of the numberOfParameters property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfParameters() {
        return numberOfParameters;
    }

    /**
     * Sets the value of the numberOfParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfParameters(BigInteger value) {
        this.numberOfParameters = value;
    }

    /**
     * Gets the value of the logisticRegressionModelStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogisticRegressionModelStatus() {
        return logisticRegressionModelStatus;
    }

    /**
     * Sets the value of the logisticRegressionModelStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogisticRegressionModelStatus(String value) {
        this.logisticRegressionModelStatus = value;
    }

    /**
     * Gets the value of the aic property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAic() {
        return aic;
    }

    /**
     * Sets the value of the aic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAic(BigDecimal value) {
        this.aic = value;
    }

    /**
     * Gets the value of the bic property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBic() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBic(Float value) {
        this.bic = value;
    }

    /**
     * Gets the value of the logLikelihood property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getLogLikelihood() {
        return logLikelihood;
    }

    /**
     * Sets the value of the logLikelihood property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLogLikelihood(Float value) {
        this.logLikelihood = value;
    }

    /**
     * Gets the value of the crossValidationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrossValidationStatus() {
        return crossValidationStatus;
    }

    /**
     * Sets the value of the crossValidationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrossValidationStatus(String value) {
        this.crossValidationStatus = value;
    }

    /**
     * Gets the value of the unstratifiedCrossValidationRmse property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getUnstratifiedCrossValidationRmse() {
        return unstratifiedCrossValidationRmse;
    }

    /**
     * Sets the value of the unstratifiedCrossValidationRmse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setUnstratifiedCrossValidationRmse(Float value) {
        this.unstratifiedCrossValidationRmse = value;
    }

    /**
     * Gets the value of the studentStratifiedCrossValidationRmse property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getStudentStratifiedCrossValidationRmse() {
        return studentStratifiedCrossValidationRmse;
    }

    /**
     * Sets the value of the studentStratifiedCrossValidationRmse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setStudentStratifiedCrossValidationRmse(Float value) {
        this.studentStratifiedCrossValidationRmse = value;
    }

    /**
     * Gets the value of the stepStratifiedCrossValidationRmse property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getStepStratifiedCrossValidationRmse() {
        return stepStratifiedCrossValidationRmse;
    }

    /**
     * Sets the value of the stepStratifiedCrossValidationRmse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setStepStratifiedCrossValidationRmse(Float value) {
        this.stepStratifiedCrossValidationRmse = value;
    }

    /**
     * Gets the value of the unstratifiedNumberOfParameters property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnstratifiedNumberOfParameters() {
        return unstratifiedNumberOfParameters;
    }

    /**
     * Sets the value of the unstratifiedNumberOfParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnstratifiedNumberOfParameters(BigInteger value) {
        this.unstratifiedNumberOfParameters = value;
    }

    /**
     * Gets the value of the unstratifiedNumberOfObservations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnstratifiedNumberOfObservations() {
        return unstratifiedNumberOfObservations;
    }

    /**
     * Sets the value of the unstratifiedNumberOfObservations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnstratifiedNumberOfObservations(BigInteger value) {
        this.unstratifiedNumberOfObservations = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
