//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.08 at 04:54:09 PM CET 
//


package com.lisilab.its.model.datashop;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LogLikelihood_QNAME = new QName("", "log_likelihood");
    private final static QName _ObservationsWithKcs_QNAME = new QName("", "observations_with_kcs");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Level_QNAME = new QName("", "level");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _CrossValidationStatus_QNAME = new QName("", "cross_validation_status");
    private final static QName _KcModelName_QNAME = new QName("", "kc_model_name");
    private final static QName _NumberOfAccessibleSamples_QNAME = new QName("", "number_of_accessible_samples");
    private final static QName _LogisticRegressionModelStatus_QNAME = new QName("", "logistic_regression_model_status");
    private final static QName _NumberOfKcModels_QNAME = new QName("", "number_of_kc_models");
    private final static QName _NumberOfSteps_QNAME = new QName("", "number_of_steps");
    private final static QName _NumberOfTransactions_QNAME = new QName("", "number_of_transactions");
    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _NumberOfSamples_QNAME = new QName("", "number_of_samples");
    private final static QName _Project_QNAME = new QName("", "project");
    private final static QName _UnstratifiedNumberOfParameters_QNAME = new QName("", "unstratified_number_of_parameters");
    private final static QName _UnstratifiedCrossValidationRmse_QNAME = new QName("", "unstratified_cross_validation_rmse");
    private final static QName _Owner_QNAME = new QName("", "owner");
    private final static QName _Column_QNAME = new QName("", "column");
    private final static QName _Curriculum_QNAME = new QName("", "curriculum");
    private final static QName _AdditionalNotes_QNAME = new QName("", "additional_notes");
    private final static QName _Pi_QNAME = new QName("", "pi");
    private final static QName _NumberOfUniqueSteps_QNAME = new QName("", "number_of_unique_steps");
    private final static QName _FileName_QNAME = new QName("", "file_name");
    private final static QName _Aic_QNAME = new QName("", "aic");
    private final static QName _UniqueId_QNAME = new QName("", "unique_id");
    private final static QName _Released_QNAME = new QName("", "released");
    private final static QName _NumberOfStudents_QNAME = new QName("", "number_of_students");
    private final static QName _EndDate_QNAME = new QName("", "end_date");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _StepStratifiedCrossValidationRmse_QNAME = new QName("", "step_stratified_cross_validation_rmse");
    private final static QName _Tutor_QNAME = new QName("", "tutor");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _NumberOfKcs_QNAME = new QName("", "number_of_kcs");
    private final static QName _Domain_QNAME = new QName("", "domain");
    private final static QName _Hypothesis_QNAME = new QName("", "hypothesis");
    private final static QName _Bic_QNAME = new QName("", "bic");
    private final static QName _Learnlab_QNAME = new QName("", "learnlab");
    private final static QName _DataProvider_QNAME = new QName("", "data_provider");
    private final static QName _Added_QNAME = new QName("", "added");
    private final static QName _HasStudyData_QNAME = new QName("", "has_study_data");
    private final static QName _FilterText_QNAME = new QName("", "filter_text");
    private final static QName _Access_QNAME = new QName("", "access");
    private final static QName _Operator_QNAME = new QName("", "operator");
    private final static QName _NumberOfParameters_QNAME = new QName("", "number_of_parameters");
    private final static QName _School_QNAME = new QName("", "school");
    private final static QName _StudentStratifiedCrossValidationRmse_QNAME = new QName("", "student_stratified_cross_validation_rmse");
    private final static QName _UnstratifiedNumberOfObservations_QNAME = new QName("", "unstratified_number_of_observations");
    private final static QName _StatisticalModel_QNAME = new QName("", "statistical_model");
    private final static QName _Public_QNAME = new QName("", "public");
    private final static QName _StartDate_QNAME = new QName("", "start_date");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PslcDatashopMessage }
     * 
     */
    public PslcDatashopMessage createPslcDatashopMessage() {
        return new PslcDatashopMessage();
    }

    /**
     * Create an instance of {@link Dataset }
     * 
     */
    public Dataset createDataset() {
        return new Dataset();
    }

    /**
     * Create an instance of {@link KcModel }
     * 
     */
    public KcModel createKcModel() {
        return new KcModel();
    }

    /**
     * Create an instance of {@link Sample }
     * 
     */
    public Sample createSample() {
        return new Sample();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link Analysis }
     * 
     */
    public Analysis createAnalysis() {
        return new Analysis();
    }

    /**
     * Create an instance of {@link CustomField }
     * 
     */
    public CustomField createCustomField() {
        return new CustomField();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "log_likelihood")
    public JAXBElement<Float> createLogLikelihood(Float value) {
        return new JAXBElement<Float>(_LogLikelihood_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "observations_with_kcs")
    public JAXBElement<BigInteger> createObservationsWithKcs(BigInteger value) {
        return new JAXBElement<BigInteger>(_ObservationsWithKcs_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "level")
    public JAXBElement<String> createLevel(String value) {
        return new JAXBElement<String>(_Level_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cross_validation_status")
    public JAXBElement<String> createCrossValidationStatus(String value) {
        return new JAXBElement<String>(_CrossValidationStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kc_model_name")
    public JAXBElement<String> createKcModelName(String value) {
        return new JAXBElement<String>(_KcModelName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_accessible_samples")
    public JAXBElement<BigInteger> createNumberOfAccessibleSamples(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfAccessibleSamples_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "logistic_regression_model_status")
    public JAXBElement<String> createLogisticRegressionModelStatus(String value) {
        return new JAXBElement<String>(_LogisticRegressionModelStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_kc_models")
    public JAXBElement<BigInteger> createNumberOfKcModels(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfKcModels_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_steps")
    public JAXBElement<BigInteger> createNumberOfSteps(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfSteps_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_transactions")
    public JAXBElement<BigInteger> createNumberOfTransactions(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfTransactions_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_samples")
    public JAXBElement<BigInteger> createNumberOfSamples(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfSamples_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "project")
    public JAXBElement<String> createProject(String value) {
        return new JAXBElement<String>(_Project_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unstratified_number_of_parameters")
    public JAXBElement<BigInteger> createUnstratifiedNumberOfParameters(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnstratifiedNumberOfParameters_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unstratified_cross_validation_rmse")
    public JAXBElement<Float> createUnstratifiedCrossValidationRmse(Float value) {
        return new JAXBElement<Float>(_UnstratifiedCrossValidationRmse_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "owner")
    public JAXBElement<String> createOwner(String value) {
        return new JAXBElement<String>(_Owner_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "column")
    public JAXBElement<String> createColumn(String value) {
        return new JAXBElement<String>(_Column_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "curriculum")
    public JAXBElement<String> createCurriculum(String value) {
        return new JAXBElement<String>(_Curriculum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "additional_notes")
    public JAXBElement<String> createAdditionalNotes(String value) {
        return new JAXBElement<String>(_AdditionalNotes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pi")
    public JAXBElement<String> createPi(String value) {
        return new JAXBElement<String>(_Pi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_unique_steps")
    public JAXBElement<BigInteger> createNumberOfUniqueSteps(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfUniqueSteps_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "file_name")
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "aic")
    public JAXBElement<BigDecimal> createAic(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Aic_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unique_id")
    public JAXBElement<BigInteger> createUniqueId(BigInteger value) {
        return new JAXBElement<BigInteger>(_UniqueId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "released")
    public JAXBElement<String> createReleased(String value) {
        return new JAXBElement<String>(_Released_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_students")
    public JAXBElement<BigInteger> createNumberOfStudents(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfStudents_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "end_date")
    public JAXBElement<XMLGregorianCalendar> createEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EndDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "step_stratified_cross_validation_rmse")
    public JAXBElement<Float> createStepStratifiedCrossValidationRmse(Float value) {
        return new JAXBElement<Float>(_StepStratifiedCrossValidationRmse_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tutor")
    public JAXBElement<String> createTutor(String value) {
        return new JAXBElement<String>(_Tutor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_kcs")
    public JAXBElement<BigInteger> createNumberOfKcs(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfKcs_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "domain")
    public JAXBElement<String> createDomain(String value) {
        return new JAXBElement<String>(_Domain_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hypothesis")
    public JAXBElement<String> createHypothesis(String value) {
        return new JAXBElement<String>(_Hypothesis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bic")
    public JAXBElement<Float> createBic(Float value) {
        return new JAXBElement<Float>(_Bic_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "learnlab")
    public JAXBElement<String> createLearnlab(String value) {
        return new JAXBElement<String>(_Learnlab_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "data_provider")
    public JAXBElement<String> createDataProvider(String value) {
        return new JAXBElement<String>(_DataProvider_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "added")
    public JAXBElement<XMLGregorianCalendar> createAdded(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Added_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "has_study_data")
    public JAXBElement<String> createHasStudyData(String value) {
        return new JAXBElement<String>(_HasStudyData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filter_text")
    public JAXBElement<String> createFilterText(String value) {
        return new JAXBElement<String>(_FilterText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "access")
    public JAXBElement<String> createAccess(String value) {
        return new JAXBElement<String>(_Access_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "operator")
    public JAXBElement<String> createOperator(String value) {
        return new JAXBElement<String>(_Operator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_parameters")
    public JAXBElement<BigInteger> createNumberOfParameters(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfParameters_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "school")
    public JAXBElement<String> createSchool(String value) {
        return new JAXBElement<String>(_School_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "student_stratified_cross_validation_rmse")
    public JAXBElement<Float> createStudentStratifiedCrossValidationRmse(Float value) {
        return new JAXBElement<Float>(_StudentStratifiedCrossValidationRmse_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unstratified_number_of_observations")
    public JAXBElement<BigInteger> createUnstratifiedNumberOfObservations(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnstratifiedNumberOfObservations_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "statistical_model")
    public JAXBElement<String> createStatisticalModel(String value) {
        return new JAXBElement<String>(_StatisticalModel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "public")
    public JAXBElement<String> createPublic(String value) {
        return new JAXBElement<String>(_Public_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "start_date")
    public JAXBElement<XMLGregorianCalendar> createStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_StartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
